sudo: required

language: generic

matrix:
  include:
#    - os: linux
#      dist: trusty
#      python: "2.7"
#    - os: linux
#      dist: trusty
#      python: "3.5"
    - os: osx
      osx_image: xcode7
      python: "2.7"
    - os: osx
      osx_image: xcode7
      python: "3.5"

services:
  - docker

install:
  - ./test/travis-ci/install.sh
  - source setup-env.sh

script:
  - ./test/travis-ci/run_test.sh --docker-image=ray-project/ray:test-base 'source setup-env.sh && cd test && python runtest.py'
  - ./test/travis-ci/run_test.sh --docker-image=ray-project/ray:test-base 'source setup-env.sh && cd test && python array_test.py'
  - ./test/travis-ci/run_test.sh --docker-image=ray-project/ray:test-base 'source setup-env.sh && cd test && python failure_test.py'
  - ./test/travis-ci/run_test.sh --docker-image=ray-project/ray:test-base 'source setup-env.sh && cd test && python microbenchmarks.py'
  - ./test/travis-ci/run_test.sh --docker-only --shm-size=500m --docker-image=ray-project/ray:test-examples 'source setup-env.sh && cd examples/hyperopt && python driver.py'
  - ./test/travis-ci/run_test.sh --docker-only --shm-size=500m --docker-image=ray-project/ray:test-examples 'source setup-env.sh && cd examples/lbfgs && python driver.py'
